package dk.statsbiblioteket.newspaper.metadatachecker.mockers;

import dk.statsbiblioteket.medieplatform.autonomous.Batch;
import dk.statsbiblioteket.medieplatform.autonomous.iterator.common.AttributeParsingEvent;

import java.io.ByteArrayInputStream;
import java.io.IOException;
import java.io.InputStream;
import java.io.UnsupportedEncodingException;

public class JpylyzerMocker {


    public static AttributeParsingEvent getJpylyzerXmlAttributeParsingEvent(final String film, final String avisID,
                                                                            final Batch batch, final Integer size,
                                                                            final Integer width, final Integer height) {
        return new AttributeParsingEvent(
                batch.getFullID() + "/" +
                batch.getBatchID() + "-" + film + "/" +
                avisID + "-" + batch.getBatchID() + "-" + film + ".jpylyzer.xml") {
            @Override
            public InputStream getData() throws IOException {
                return new ByteArrayInputStream(
                        getFilmXml(size, width, height));
            }

            @Override
            public String getChecksum() throws IOException {
                return null;
            }
        };
    }

    public static byte[] getFilmXml(final Integer size, final Integer width, final Integer height) {
        try {

            String jpylyzer = "<?xml version='1.0' encoding='UTF-8'?>\n" +
                              "<jpylyzer>\n" +
                              "    <toolInfo>\n" +
                              "        <toolName>jpylyzer.py</toolName>\n" +
                              "        <toolVersion>1.10.1</toolVersion>\n" +
                              "    </toolInfo>\n" +
                              "    <fileInfo>\n" +
                              "        <fileName>adresseavisen1759-1795-06-13-01-0006.jp2</fileName>\n" +
                              "        <filePath>\n" +
                              "            /home/abr/newspaper-test-data/small-test-batch/B400022028241-RT1/400022028241-1/1795-06-13-01/adresseavisen1759-1795-06-13-01-0006.jp2\n" +
                              "        </filePath>\n" +
                              "        <fileSizeInBytes>" + size + "</fileSizeInBytes>\n" +
                              "        <fileLastModified>Thu Nov 14 14:36:57 2013</fileLastModified>\n" +
                              "    </fileInfo>\n" +
                              "    <isValidJP2>True</isValidJP2>\n" +
                              "    <tests/>\n" +
                              "    <properties>\n" +
                              "        <signatureBox/>\n" +
                              "        <fileTypeBox>\n" +
                              "            <br>jp2</br>\n" +
                              "            <minV>0</minV>\n" +
                              "            <cL>jp2</cL>\n" +
                              "        </fileTypeBox>\n" +
                              "        <jp2HeaderBox>\n" +
                              "            <imageHeaderBox>\n" +
                              "                <height>" + height + "</height>\n" +
                              "                <width>" + width + "</width>\n" +
                              "                <nC>1</nC>\n" +
                              "                <bPCSign>unsigned</bPCSign>\n" +
                              "                <bPCDepth>8</bPCDepth>\n" +
                              "                <c>jpeg2000</c>\n" +
                              "                <unkC>yes</unkC>\n" +
                              "                <iPR>no</iPR>\n" +
                              "            </imageHeaderBox>\n" +
                              "            <colourSpecificationBox>\n" +
                              "                <meth>Enumerated</meth>\n" +
                              "                <prec>0</prec>\n" +
                              "                <approx>0</approx>\n" +
                              "                <enumCS>greyscale</enumCS>\n" +
                              "            </colourSpecificationBox>\n" +
                              "            <resolutionBox>\n" +
                              "                <captureResolutionBox>\n" +
                              "                    <vRcN>30000</vRcN>\n" +
                              "                    <vRcD>254</vRcD>\n" +
                              "                    <hRcN>30000</hRcN>\n" +
                              "                    <hRcD>254</hRcD>\n" +
                              "                    <vRcE>2</vRcE>\n" +
                              "                    <hRcE>2</hRcE>\n" +
                              "                    <vRescInPixelsPerMeter>11811.02</vRescInPixelsPerMeter>\n" +
                              "                    <hRescInPixelsPerMeter>11811.02</hRescInPixelsPerMeter>\n" +
                              "                    <vRescInPixelsPerInch>300.0</vRescInPixelsPerInch>\n" +
                              "                    <hRescInPixelsPerInch>300.0</hRescInPixelsPerInch>\n" +
                              "                </captureResolutionBox>\n" +
                              "            </resolutionBox>\n" +
                              "        </jp2HeaderBox>\n" +
                              "        <contiguousCodestreamBox>\n" +
                              "            <siz>\n" +
                              "                <lsiz>41</lsiz>\n" +
                              "                <rsiz>ISO/IEC 15444-1</rsiz>\n" +
                              "                <xsiz>2312</xsiz>\n" +
                              "                <ysiz>2859</ysiz>\n" +
                              "                <xOsiz>0</xOsiz>\n" +
                              "                <yOsiz>0</yOsiz>\n" +
                              "                <xTsiz>1024</xTsiz>\n" +
                              "                <yTsiz>1024</yTsiz>\n" +
                              "                <xTOsiz>0</xTOsiz>\n" +
                              "                <yTOsiz>0</yTOsiz>\n" +
                              "                <numberOfTiles>9</numberOfTiles>\n" +
                              "                <csiz>1</csiz>\n" +
                              "                <ssizSign>unsigned</ssizSign>\n" +
                              "                <ssizDepth>8</ssizDepth>\n" +
                              "                <xRsiz>1</xRsiz>\n" +
                              "                <yRsiz>1</yRsiz>\n" +
                              "            </siz>\n" +
                              "            <cod>\n" +
                              "                <lcod>12</lcod>\n" +
                              "                <precincts>no</precincts>\n" +
                              "                <sop>yes</sop>\n" +
                              "                <eph>yes</eph>\n" +
                              "                <order>RPCL</order>\n" +
                              "                <layers>16</layers>\n" +
                              "                <multipleComponentTransformation>no</multipleComponentTransformation>\n" +
                              "                <levels>6</levels>\n" +
                              "                <codeBlockWidth>64</codeBlockWidth>\n" +
                              "                <codeBlockHeight>64</codeBlockHeight>\n" +
                              "                <codingBypass>yes</codingBypass>\n" +
                              "                <resetOnBoundaries>no</resetOnBoundaries>\n" +
                              "                <termOnEachPass>no</termOnEachPass>\n" +
                              "                <vertCausalContext>no</vertCausalContext>\n" +
                              "                <predTermination>no</predTermination>\n" +
                              "                <segmentationSymbols>yes</segmentationSymbols>\n" +
                              "                <transformation>5-3 reversible</transformation>\n" +
                              "            </cod>\n" +
                              "            <qcd>\n" +
                              "                <lqcd>22</lqcd>\n" +
                              "                <qStyle>no quantization</qStyle>\n" +
                              "                <guardBits>1</guardBits>\n" +
                              "                <epsilon>9</epsilon>\n" +
                              "                <epsilon>10</epsilon>\n" +
                              "                <epsilon>10</epsilon>\n" +
                              "                <epsilon>11</epsilon>\n" +
                              "                <epsilon>10</epsilon>\n" +
                              "                <epsilon>10</epsilon>\n" +
                              "            </qcd>\n" +
                              "            <com>\n" +
                              "                <lcom>15</lcom>\n" +
                              "                <rcom>ISO/IEC 8859-15 (Latin)</rcom>\n" +
                              "                <comment>Kakadu-v7.2</comment>\n" +
                              "            </com>\n" +
                              "            <com>\n" +
                              "                <lcom>347</lcom>\n" +
                              "                <rcom>ISO/IEC 8859-15 (Latin)</rcom>\n" +
                              "                <comment>Kdu-Layer-Info: log_2{Delta-D(squared-error)/Delta-L(bytes)}, L(bytes)*-175.6, 3.6e+006*-176.8,\n" +
                              "                    3.6e+006*-177.9, 3.6e+006*-179.1, 3.6e+006*-180.3, 3.6e+006*-181.5, 3.7e+006*-182.6,\n" +
                              "                    3.7e+006*-183.8, 3.7e+006*-185.0, 3.7e+006*-186.1, 3.7e+006*-187.3, 3.7e+006*-188.5,\n" +
                              "                    3.7e+006*-189.7, 3.7e+006*-190.8, 3.7e+006*-192.0, 3.7e+006*-192.0, 6.6e+006*\n" +
                              "                </comment>\n" +
                              "            </com>\n" +
                              "            <tileParts>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>0</isot>\n" +
                              "                        <psot>415</psot>\n" +
                              "                        <tpsot>0</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>1</isot>\n" +
                              "                        <psot>406</psot>\n" +
                              "                        <tpsot>0</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>2</isot>\n" +
                              "                        <psot>246</psot>\n" +
                              "                        <tpsot>0</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>3</isot>\n" +
                              "                        <psot>394</psot>\n" +
                              "                        <tpsot>0</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>4</isot>\n" +
                              "                        <psot>403</psot>\n" +
                              "                        <tpsot>0</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>5</isot>\n" +
                              "                        <psot>238</psot>\n" +
                              "                        <tpsot>0</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>6</isot>\n" +
                              "                        <psot>353</psot>\n" +
                              "                        <tpsot>0</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>7</isot>\n" +
                              "                        <psot>346</psot>\n" +
                              "                        <tpsot>0</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>8</isot>\n" +
                              "                        <psot>229</psot>\n" +
                              "                        <tpsot>0</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>0</isot>\n" +
                              "                        <psot>923</psot>\n" +
                              "                        <tpsot>1</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>1</isot>\n" +
                              "                        <psot>923</psot>\n" +
                              "                        <tpsot>1</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>2</isot>\n" +
                              "                        <psot>368</psot>\n" +
                              "                        <tpsot>1</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>3</isot>\n" +
                              "                        <psot>942</psot>\n" +
                              "                        <tpsot>1</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>4</isot>\n" +
                              "                        <psot>941</psot>\n" +
                              "                        <tpsot>1</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>5</isot>\n" +
                              "                        <psot>345</psot>\n" +
                              "                        <tpsot>1</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>6</isot>\n" +
                              "                        <psot>655</psot>\n" +
                              "                        <tpsot>1</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>7</isot>\n" +
                              "                        <psot>659</psot>\n" +
                              "                        <tpsot>1</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>8</isot>\n" +
                              "                        <psot>326</psot>\n" +
                              "                        <tpsot>1</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>0</isot>\n" +
                              "                        <psot>2999</psot>\n" +
                              "                        <tpsot>2</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>1</isot>\n" +
                              "                        <psot>2935</psot>\n" +
                              "                        <tpsot>2</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>2</isot>\n" +
                              "                        <psot>818</psot>\n" +
                              "                        <tpsot>2</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>3</isot>\n" +
                              "                        <psot>3228</psot>\n" +
                              "                        <tpsot>2</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>4</isot>\n" +
                              "                        <psot>3258</psot>\n" +
                              "                        <tpsot>2</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>5</isot>\n" +
                              "                        <psot>744</psot>\n" +
                              "                        <tpsot>2</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>6</isot>\n" +
                              "                        <psot>1866</psot>\n" +
                              "                        <tpsot>2</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>7</isot>\n" +
                              "                        <psot>1892</psot>\n" +
                              "                        <tpsot>2</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>8</isot>\n" +
                              "                        <psot>638</psot>\n" +
                              "                        <tpsot>2</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>0</isot>\n" +
                              "                        <psot>10644</psot>\n" +
                              "                        <tpsot>3</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>1</isot>\n" +
                              "                        <psot>10571</psot>\n" +
                              "                        <tpsot>3</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>2</isot>\n" +
                              "                        <psot>2420</psot>\n" +
                              "                        <tpsot>3</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>3</isot>\n" +
                              "                        <psot>12259</psot>\n" +
                              "                        <tpsot>3</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>4</isot>\n" +
                              "                        <psot>12242</psot>\n" +
                              "                        <tpsot>3</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>5</isot>\n" +
                              "                        <psot>2215</psot>\n" +
                              "                        <tpsot>3</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>6</isot>\n" +
                              "                        <psot>6506</psot>\n" +
                              "                        <tpsot>3</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>7</isot>\n" +
                              "                        <psot>6737</psot>\n" +
                              "                        <tpsot>3</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>8</isot>\n" +
                              "                        <psot>1757</psot>\n" +
                              "                        <tpsot>3</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>0</isot>\n" +
                              "                        <psot>38750</psot>\n" +
                              "                        <tpsot>4</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>1</isot>\n" +
                              "                        <psot>38006</psot>\n" +
                              "                        <tpsot>4</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>2</isot>\n" +
                              "                        <psot>8271</psot>\n" +
                              "                        <tpsot>4</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>3</isot>\n" +
                              "                        <psot>46375</psot>\n" +
                              "                        <tpsot>4</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>4</isot>\n" +
                              "                        <psot>45894</psot>\n" +
                              "                        <tpsot>4</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>5</isot>\n" +
                              "                        <psot>7668</psot>\n" +
                              "                        <tpsot>4</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>6</isot>\n" +
                              "                        <psot>23644</psot>\n" +
                              "                        <tpsot>4</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>7</isot>\n" +
                              "                        <psot>25645</psot>\n" +
                              "                        <tpsot>4</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>8</isot>\n" +
                              "                        <psot>5646</psot>\n" +
                              "                        <tpsot>4</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>0</isot>\n" +
                              "                        <psot>131213</psot>\n" +
                              "                        <tpsot>5</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>1</isot>\n" +
                              "                        <psot>130633</psot>\n" +
                              "                        <tpsot>5</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>2</isot>\n" +
                              "                        <psot>28136</psot>\n" +
                              "                        <tpsot>5</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>3</isot>\n" +
                              "                        <psot>156049</psot>\n" +
                              "                        <tpsot>5</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>4</isot>\n" +
                              "                        <psot>154013</psot>\n" +
                              "                        <tpsot>5</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>5</isot>\n" +
                              "                        <psot>26877</psot>\n" +
                              "                        <tpsot>5</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>6</isot>\n" +
                              "                        <psot>84513</psot>\n" +
                              "                        <tpsot>5</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>7</isot>\n" +
                              "                        <psot>92448</psot>\n" +
                              "                        <tpsot>5</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>8</isot>\n" +
                              "                        <psot>19126</psot>\n" +
                              "                        <tpsot>5</tpsot>\n" +
                              "                        <tnsot>0</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>0</isot>\n" +
                              "                        <psot>398182</psot>\n" +
                              "                        <tpsot>6</tpsot>\n" +
                              "                        <tnsot>7</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>1</isot>\n" +
                              "                        <psot>397002</psot>\n" +
                              "                        <tpsot>6</tpsot>\n" +
                              "                        <tnsot>7</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>2</isot>\n" +
                              "                        <psot>85024</psot>\n" +
                              "                        <tpsot>6</tpsot>\n" +
                              "                        <tnsot>7</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>3</isot>\n" +
                              "                        <psot>470040</psot>\n" +
                              "                        <tpsot>6</tpsot>\n" +
                              "                        <tnsot>7</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>4</isot>\n" +
                              "                        <psot>460636</psot>\n" +
                              "                        <tpsot>6</tpsot>\n" +
                              "                        <tnsot>7</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>5</isot>\n" +
                              "                        <psot>83630</psot>\n" +
                              "                        <tpsot>6</tpsot>\n" +
                              "                        <tnsot>7</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>6</isot>\n" +
                              "                        <psot>264834</psot>\n" +
                              "                        <tpsot>6</tpsot>\n" +
                              "                        <tnsot>7</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>7</isot>\n" +
                              "                        <psot>289525</psot>\n" +
                              "                        <tpsot>6</tpsot>\n" +
                              "                        <tnsot>7</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "                <tilePart>\n" +
                              "                    <sot>\n" +
                              "                        <lsot>10</lsot>\n" +
                              "                        <isot>8</isot>\n" +
                              "                        <psot>57149</psot>\n" +
                              "                        <tpsot>6</tpsot>\n" +
                              "                        <tnsot>7</tnsot>\n" +
                              "                    </sot>\n" +
                              "                </tilePart>\n" +
                              "            </tileParts>\n" +
                              "        </contiguousCodestreamBox>\n" +
                              "        <compressionRatio>1.8</compressionRatio>\n" +
                              "    </properties>\n" +
                              "</jpylyzer>";

            return jpylyzer.getBytes("UTF-8");
        } catch (UnsupportedEncodingException e) {
            throw new Error(e);
        }
    }
}
